name: 'Box Upload'
description: 'Uploads a file to Box'
inputs:
  box-client-sdk-config:
    description: JSON string downloaded from the Box Developer Console.
    required: true
  box-folder-id:
    description: Box folder ID for the destination. Can be found in the URL.
    required: true
  file:
    description: File to upload.
    required: true
  destination-filename:
    description: Destination filename in Box. If not specified, source filename will be used.

outputs:
  shared-link:
    description: Shared link of the folder in Box, if it exists.

runs:
  using: 'node20'
  main: 'dist/index.js'